-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit ;


PACKAGE TASTE_Dataview with SPARK_Mode
IS


SUBTYPE OctStr_index is integer range 1..10;
SUBTYPE OctStr_array IS adaasn1rtl.OctetBuffer(OctStr_index);
SUBTYPE OctStr_length_index is integer range 0..10;
TYPE OctStr IS  RECORD
    Length : OctStr_length_index;
    Data  : OctStr_array;
END RECORD;

function OctStr_Equal(val1, val2: in OctStr) return Boolean;

function OctStr_Init return OctStr;

ERR_OCTSTR:CONSTANT INTEGER := 1; -- 
FUNCTION OctStr_IsConstraintValid(val : in OctStr) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide TASTE_Dataview;


END TASTE_Dataview;