-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit ;


PACKAGE TASTE_Dataview with SPARK_Mode
IS


-- MySeqOf --------------------------------------------
SUBTYPE MySeqOf_index is integer range 1..5;
TYPE MySeqOf_array IS ARRAY (MySeqOf_index) OF adaasn1rtl.Asn1Boolean;
SUBTYPE MySeqOf_length_index is integer range 0..5;
TYPE MySeqOf IS  RECORD
    Length : MySeqOf_length_index;
    Data  : MySeqOf_array;
END RECORD;

function MySeqOf_Equal(val1, val2: in MySeqOf) return Boolean;

function MySeqOf_Init return MySeqOf;

ERR_MYSEQOF_ELM:CONSTANT INTEGER := 1; 
ERR_MYSEQOF:CONSTANT INTEGER := 8; 
FUNCTION MySeqOf_IsConstraintValid(val : in MySeqOf) return adaasn1rtl.ASN1_RESULT;
-- MySeqOf2 --------------------------------------------
SUBTYPE MySeqOf2_index is integer range 1..2;
TYPE MySeqOf2_array IS ARRAY (MySeqOf2_index) OF MySeqOf;
SUBTYPE MySeqOf2_length_index is integer range 0..2;
TYPE MySeqOf2 IS  RECORD
    Length : MySeqOf2_length_index;
    Data  : MySeqOf2_array;
END RECORD;

function MySeqOf2_Equal(val1, val2: in MySeqOf2) return Boolean;

function MySeqOf2_Init return MySeqOf2;

ERR_MYSEQOF2_ELM_ELM:CONSTANT INTEGER := 15; 
ERR_MYSEQOF2_ELM:CONSTANT INTEGER := 22; 
ERR_MYSEQOF2:CONSTANT INTEGER := 33; 
FUNCTION MySeqOf2_IsConstraintValid(val : in MySeqOf2) return adaasn1rtl.ASN1_RESULT;
-- MySeq --------------------------------------------
SUBTYPE MySeq_b is adaasn1rtl.Asn1UInt range 0 .. 255;


TYPE MySeq IS RECORD 
    a : adaasn1rtl.Asn1Boolean;
    b : MySeq_b;
END RECORD;

function MySeq_b_Equal(val1, val2: in MySeq_b) return Boolean;

function MySeq_Equal(val1, val2: in MySeq) return Boolean;

function MySeq_b_Init return MySeq_b;
function MySeq_Init return MySeq;

ERR_MYSEQ_A:CONSTANT INTEGER := 40; 
ERR_MYSEQ_B:CONSTANT INTEGER := 47; 
FUNCTION MySeq_IsConstraintValid(val : in MySeq) return adaasn1rtl.ASN1_RESULT;
-- MySeqOf3 --------------------------------------------
SUBTYPE MySeqOf3_index is integer range 1..3;
TYPE MySeqOf3_array IS ARRAY (MySeqOf3_index) OF MySeq;
TYPE MySeqOf3 IS  RECORD
    Data  : MySeqOf3_array;
END RECORD;

function MySeqOf3_Equal(val1, val2: in MySeqOf3) return Boolean;

function MySeqOf3_Init return MySeqOf3;

ERR_MYSEQOF3_ELM_A:CONSTANT INTEGER := 60; 
ERR_MYSEQOF3_ELM_B:CONSTANT INTEGER := 67; 
FUNCTION MySeqOf3_IsConstraintValid(val : in MySeqOf3) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide TASTE_Dataview;


END TASTE_Dataview;