-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
WITH TASTE_BasicTypes; use TASTE_BasicTypes;
--# inherit TASTE_BasicTypes;


PACKAGE TASTE_Dataview with SPARK_Mode
IS


-- CountTab --------------------------------------------
SUBTYPE CountTab_index is integer range 1..20;
TYPE CountTab_array IS ARRAY (CountTab_index) OF TASTE_BasicTypes.T_UInt32;
TYPE CountTab IS  RECORD
    Data  : CountTab_array;
END RECORD;

function CountTab_Equal(val1, val2: in CountTab) return Boolean;

function CountTab_Init return CountTab;

ERR_COUNTTAB_ELM:CONSTANT INTEGER := 75; 
FUNCTION CountTab_IsConstraintValid(val : in CountTab) return adaasn1rtl.ASN1_RESULT;

challenge : CONSTANT TASTE_BasicTypes.T_UInt32:= 18;
bound : CONSTANT TASTE_BasicTypes.T_UInt32:= 1000000;
nb_bit : CONSTANT TASTE_BasicTypes.T_UInt32:= 20;
val_max : CONSTANT TASTE_BasicTypes.T_UInt32:= 1048575;
count_max : CONSTANT TASTE_BasicTypes.T_UInt32:= 524288;
exceed_nb : CONSTANT TASTE_BasicTypes.T_UInt32:= 48575; 

private
   --# hide TASTE_Dataview;


END TASTE_Dataview;