-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit ;


PACKAGE EnvironmentInterfaces with SPARK_Mode
IS


SUBTYPE T_N2 is adaasn1rtl.Asn1Boolean;


function T_N2_Equal(val1, val2: in T_N2) return Boolean;

function T_N2_Init return T_N2;

ERR_T_N2:CONSTANT INTEGER := 3728; -- 
FUNCTION T_N2_IsConstraintValid(val : in T_N2) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide EnvironmentInterfaces;


END EnvironmentInterfaces;