-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;


PACKAGE BODY Environment with SPARK_Mode IS




function T_N1_Equal(val1, val2: in T_N1)
    return Boolean 
is
begin
	return val1 = val2;

end T_N1_Equal;

function T_N1_Init return T_N1
is
    val: T_N1;
begin
    val := FALSE;
    return val;
end T_N1_Init;

FUNCTION T_N1_IsConstraintValid(val : in T_N1) return adaasn1rtl.ASN1_RESULT
IS
    ret : adaasn1rtl.ASN1_RESULT;
BEGIN
    ret := adaasn1rtl.ASN1_RESULT'(Success => TRUE, ErrorCode => ERR_T_N1);
    RETURN ret;
END T_N1_IsConstraintValid;


 

END Environment;