-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit ;


PACKAGE TASTE_Dataview with SPARK_Mode
IS


SUBTYPE Light_index_range is integer range 0..3;
TYPE Light IS (red, yellow, green, all_off) with Convention => C;
for Light use
    (red => 0, yellow => 1, green => 2, all_off => 3);

function Light_Equal(val1, val2: in Light) return Boolean;

function Light_Init return Light;

ERR_LIGHT:CONSTANT INTEGER := 36; -- 
FUNCTION Light_IsConstraintValid(val : in Light) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide TASTE_Dataview;


END TASTE_Dataview;