-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
WITH Seds; use Seds;
--# inherit Seds;


PACKAGE Mission with SPARK_Mode
IS


-- MissionArray --------------------------------------------
SUBTYPE MissionArray_index is integer range 1..22;
TYPE MissionArray_array IS ARRAY (MissionArray_index) OF Seds.SedsUint8;
TYPE MissionArray IS  RECORD
    Data  : MissionArray_array;
END RECORD;

function MissionArray_Equal(val1, val2: in MissionArray) return Boolean;

function MissionArray_Init return MissionArray;

ERR_MISSIONARRAY_ELM:CONSTANT INTEGER := 1207; 
FUNCTION MissionArray_IsConstraintValid(val : in MissionArray) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide Mission;


END Mission;