-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit ;


PACKAGE CcsdsSoisSubnetwork with SPARK_Mode
IS


SUBTYPE X is adaasn1rtl.Asn1NullType;


function X_Equal(val1, val2: in X) return Boolean;

function X_Init return X;
SUBTYPE CcsdsSoisSubnetworkOctet is adaasn1rtl.Asn1UInt range 0 .. 255;


function CcsdsSoisSubnetworkOctet_Equal(val1, val2: in CcsdsSoisSubnetworkOctet) return Boolean;

function CcsdsSoisSubnetworkOctet_Init return CcsdsSoisSubnetworkOctet;

ERR_CCSDSSOISSUBNETWORKOCTET:CONSTANT INTEGER := 7; -- 
FUNCTION CcsdsSoisSubnetworkOctet_IsConstraintValid(val : in CcsdsSoisSubnetworkOctet) return adaasn1rtl.ASN1_RESULT;
SUBTYPE CcsdsSoisSubnetworkMemoryIDType is adaasn1rtl.Asn1UInt range 0 .. 65535;


function CcsdsSoisSubnetworkMemoryIDType_Equal(val1, val2: in CcsdsSoisSubnetworkMemoryIDType) return Boolean;

function CcsdsSoisSubnetworkMemoryIDType_Init return CcsdsSoisSubnetworkMemoryIDType;

ERR_CCSDSSOISSUBNETWORKMEMORYIDTYPE:CONSTANT INTEGER := 14; -- 
FUNCTION CcsdsSoisSubnetworkMemoryIDType_IsConstraintValid(val : in CcsdsSoisSubnetworkMemoryIDType) return adaasn1rtl.ASN1_RESULT;
SUBTYPE CcsdsSoisSubnetworkMemoryAddressType is adaasn1rtl.Asn1UInt range 0 .. 4294967295;


function CcsdsSoisSubnetworkMemoryAddressType_Equal(val1, val2: in CcsdsSoisSubnetworkMemoryAddressType) return Boolean;

function CcsdsSoisSubnetworkMemoryAddressType_Init return CcsdsSoisSubnetworkMemoryAddressType;

ERR_CCSDSSOISSUBNETWORKMEMORYADDRESSTYPE:CONSTANT INTEGER := 21; -- 
FUNCTION CcsdsSoisSubnetworkMemoryAddressType_IsConstraintValid(val : in CcsdsSoisSubnetworkMemoryAddressType) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide CcsdsSoisSubnetwork;


END CcsdsSoisSubnetwork;