-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
WITH Seds;
use type Seds.SedsUint8;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;


PACKAGE BODY Mission with SPARK_Mode IS




function MissionArray_Equal(val1, val2: in MissionArray)
    return Boolean 
is
    pragma Warnings (Off, "initialization of ret has no effect");        
    ret : Boolean := TRUE;
    pragma Warnings (On, "initialization of ret has no effect");        
    i1:Integer;

begin
    i1 := val1.Data'First;
    while ret and i1 <= 22 loop
        pragma Loop_Invariant (i1 >= val1.Data'First and i1 >= val2.Data'First);
        ret := (val1.Data(i1) = val2.Data(i1));
        i1 := i1+1;
    end loop;
	return ret;

end MissionArray_Equal;

function MissionArray_Init return MissionArray
is
    val: MissionArray;
    i1:Integer;
begin
    i1 := 1;
    while i1<= 22 loop
        pragma Loop_Invariant (i1 >=1 and i1<=22);
        val.Data(i1) := Seds.SedsUint8_Init;
        i1 := i1 + 1;
    end loop;

    return val;
end MissionArray_Init;

FUNCTION MissionArray_IsConstraintValid(val : in MissionArray) return adaasn1rtl.ASN1_RESULT
IS
    pragma Warnings (Off, "initialization of ret has no effect");        
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ret has no effect");        
    i1:Integer;
BEGIN
    i1 := val.Data'First;
    while ret.Success and i1 <= 22 loop
        pragma Loop_Invariant (i1 >= val.Data'First and i1 <= 22);
        ret := adaasn1rtl.ASN1_RESULT'(Success => (val.Data(i1) <= 255), ErrorCode => ERR_MISSIONARRAY_ELM);
        i1 := i1+1;
    end loop;

    RETURN ret;
END MissionArray_IsConstraintValid;


 

END Mission;