-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit ;


PACKAGE SimpleDemo with SPARK_Mode
IS


SUBTYPE SimpleDemoMyInteger is adaasn1rtl.Asn1UInt range 0 .. 4294967295;


function SimpleDemoMyInteger_Equal(val1, val2: in SimpleDemoMyInteger) return Boolean;

function SimpleDemoMyInteger_Init return SimpleDemoMyInteger;

ERR_SIMPLEDEMOMYINTEGER:CONSTANT INTEGER := 4620; -- 
FUNCTION SimpleDemoMyInteger_IsConstraintValid(val : in SimpleDemoMyInteger) return adaasn1rtl.ASN1_RESULT;

 

private
   --# hide SimpleDemo;


END SimpleDemo;